Defensores é um projeto idealizado por Ulisses Almeida, ou seja eu, em trazer ao sistema 3D\&T uma real atualização no sistema sem perder sua essência. O objetivo dessa atualização é permitir maior flexbilidade, liberdade, opções e equlíbrio ao construir um personagem, além disso, desejo trazer regras que facilite a memorização e a improvisação. Além disso não desejo lançar a versão final só com as minhas opiniões e dos meus amigos, inspirado pela filosofia do autores do RPG Pathfinder, desejo que essa atualização tenha feedback de pessoas do Brasil inteiro que gostem de 3D\&T. 

Para construir esse sistema, não tive apenas 3D\&T como base de insipiração. Jogo RPG faz 11 anos, joguei GURPS, Daemon, AD\&D, um pouco de Vampiro e os meus preferidos: 3D\&D e 3D\&T. Não existe um jogo de RPG melhor, todos eles tem suas vantagens e desvantagens, por causa disso pode ser que você ame um e odeie outro. 

A principal vantagem do 3D\&T em relação aos demais é a sua simplicidade e facilidade de aprendizado, ou seja, em poucos minutos jogadores experientes criam seus personagens, história e jogam, enquanto os jogadores iniciantes conseguem acomapanha-los sem muita dificuldades. A desvantagem do 3D\&T é quando ocorre momentos um pouco mais complexos ou realista fica difícil de adaptar, além disso há desequilibrio de vantagens e atributos, e ainda quando os personagens evoluem demais as batalhas ficam muito demoradas e repetitivas.

Defensores mantém a simplicidade, porém traz uma "encorpada" ao sistema. Com um modificações e novidades nas regras, vantagens, desvantagens, perícias, manobras e ações. Enfim, Defensores realmente se parece com uma evolução do nosso querido 3D\&T. Segue abaixo, uma tabela de comparação básica entre o sistema 3D\&T e os Defensores, para você ter leve idéia das mudanças e das coisas legais que você encontrará.

********* TABELAAAA ****************

O objetivo do Defensores é ser uma real atualização, para deixar o jogo mais divertido e interessante. Mas como todo jogo de RPG, possui suas vantagens e desvantagens, portanto pode acontecer de você odiar o Defensores. Porém não tem problema, não ficarei chateado, com os ótimos sistemas que existem por ai, com certeza você irá encontrar um que te agrade. 
